name: File Update Notification

on:
  push:
    branches: [ master ]  # masterブランチへのプッシュ時に実行
  pull_request:
    branches: [ master ]  # masterブランチへのプルリクエスト時に実行

jobs:
  notify-file-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3　# v2から v3 に更新
      with:
        fetch-depth: 2  # 最新の2つのコミットを取得

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41 # 最新バージョンに更新（v23から v41 に）

    - name: Display changed files
      run: |
        echo "ファイルが更新されました！"
        echo "変更されたファイル:"
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file"
        done
