name: File Update Notification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  notify-file-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41

    - name: Display changed files
      run: |
        echo "ファイルが更新されました！"
        echo "変更されたファイル:"
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file"
        done
