name: File Update Notification

on:
  push:
    branches: [ main ]  # mainブランチへのプッシュ時に実行
  pull_request:
    branches: [ main ]  # mainブランチへのプルリクエスト時に実行

jobs:
  notify-file-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # 最新の2つのコミットを取得

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41

    - name: Display changed files
      run: |
        echo "ファイルが更新されました！"
        echo "変更されたファイル:"
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file"
        done
